version: '3.8'
services:
  # 1. Aplikasi Laravel (PHP)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db

  # 2. Web Server (Nginx)
  webserver:
    image: nginx:alpine
    container_name: nginx-server
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  # 3. Database (MySQL)
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: jobportal
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306" # Kita pakai port 3307 di laptop agar tidak bentrok dengan XAMPP/Laragon